### ISSUE TITLE
Computer won't boot after failed installation.

### ISSUE THREAD

**Issue by tamirco2003** [felixrieseberg/windows-build-tools#167]
I tried installing, the installer was stuck on "finished installing python 2.7".
I stopped it with ctrl+c and tried again. It said that it's still installing, and I need to wait until it finishes installing.
I restarted my computer, and now it won't even reach the desktop.
What do I do?

**Comment by jacobq** [comment]
> I restarted my computer, and now it won't even reach the desktop.

I'm sorry you are having trouble, but unfortunately it sounds like it is beyond the scope of the `windows-build-tools` project, and thus this is not the place to get support for it. All this program does is download and launch other installers (i.e. Python & Microsoft's C++ build tools, (see https://github.com/felixrieseberg/windows-build-tools/blob/master/src/constants.ts)).  If the problem you're having happened to begin occurring after attempting to install this package then I suspect it was either a coincidence (something else wrong already / failed since previous reboot) or that something was corrupted (left in an inconsistent state) by you aborting the installer. You'll likely need to proceed with general purpose recovery steps to undo whatever caused the problem (e.g. boot alternate media, scan file system for inconsistency with `chkdsk`, scan OS file signatures with `sfc`, ..., see if you can uninstall recently installed packaged, use a restore point, etc.).

See also:

* [Recovery options in Windows 10](https://support.microsoft.com/en-us/help/12415/windows-10-recovery-options)
* [How to Use All of Windows 10’s Backup and Recovery Tools](https://www.howtogeek.com/220986/how-to-use-all-of-windows-10%E2%80%99s-backup-and-recovery-tools/)
* [`CHKDSK`](https://en.wikipedia.org/wiki/CHKDSK)
* [Use SFC /Scannow to Repair Windows System Files](https://www.lifewire.com/how-to-use-sfc-scannow-to-repair-windows-system-files-2626161)
