### ISSUE TITLE
Not free for enterprise use

### ISSUE THREAD

**Issue by Ristaaf** [felixrieseberg/windows-build-tools#169]
The readme file should clarify that the build tools being installed here requires a valid license to Visual Studio. Since VS Community edition is fine, this means that the build tools are free for most people, but not for enterprise use!

https://social.msdn.microsoft.com/Forums/en-US/08d62115-0b51-484f-afda-229989be9263/license-for-visual-c-2017-build-tools?forum=visualstudiogeneral

So it should say something like (from the link above)
"In non-enterprise organizations, up to five users can use Visual Studio Community. In enterprise organizations (meaning those with >250 PCs or >$1 Million US Dollars in annual revenue), no use is permitted beyond the open source, academic research, and classroom learning environment scenarios described above."

**Comment by jacobq** [comment]
Yikes, I was unaware of that restriction (though thankfully unaffected personally). However, since it is upstream and subject to change, perhaps we should just update [`README.md`](https://github.com/felixrieseberg/windows-build-tools/blob/master/README.md#windows-build-tools) to note the nature of the license for the Microsoft package(s) we install and link to their corresponding page (rather than trying to copy it & keep in up-to-date).
