### ISSUE TITLE
[Dirty Uninstall] npm uninstall leaves all "tools" installed

### ISSUE THREAD

**Issue by itanex** [felixrieseberg/windows-build-tools#177]
When I tried removing this package it left tons of things behind that I did not want.

The following folders are still present and populated (not all listed)

* %user%/.windows-build-tools
* /program files (x86)/Windows Kits
* Program Files (x86)/Microsoft SDKs/TypeScript/2.4 // also the props file in the versions folder
* Program Files (x86)/Microsoft SDKs/Windows
* Program Files (x86)/Microsoft SDKs/Windows Kits
* Program Files (x86)/Microsoft SDKs/Windows Phone

[Update]
Parsing the logs I am finding a ton of values dropped into the registration directly from the scripts unrelated to the packages installed. What is the deal? There really needs to be a clean way to remove these artifacts.

Running 
Windows 10 - 10.0.17763 Build 17763

**Comment by felixrieseberg** [comment]
There might be confusion about what this package does - it automatically installs the Visual Studio Build tools and Python 2.7 for you by downloading and running the respective installers.

> Parsing the logs I am finding a ton of values dropped into the registration directly from the scripts unrelated to the packages installed. What is the deal? There really needs to be a clean way to remove these artifacts.

Ah, I'm so happy you've asked! Since I see that you actually work for Microsoft, I'd like to turn this around on you - there really _is a need_ for a way to cleanly install and uninstall the required artifacts for some basic C++ compilation. You're right! The Visual Studio Build Tools are sadly the actual blocker here.

Given that you've opened the issue, a PR would be _most_ appreciated, but short of that, I'd be happy about as little as instructions on how to make that happen.

**Comment by itanex** [comment]
@felixrieseberg I do not work on any of the build systems at Microsoft. I work on a small DB Migration documentation site. Your the one packaging someone else's products together, which makes you partially responsible now. Yes I installed it, but since it was labelled as Windows the name implies that you are/were at one time working with Microsoft. Since this is your repository, once could claim that your using the trademark of Windows without consent, since if you were, Microsoft would be the repository owner at that point.

That aside, I guess the only thing I can do now is "purge" my operating system on the development image I was using and continue to inform others that this is not a library that you should use directly. Maybe reference as a guide, but not use.
