### ISSUE TITLE
6 GB just to be to use node-gyp ??

### ISSUE THREAD

**Issue by AlexandraK** [felixrieseberg/windows-build-tools#202]
The level of incompetence of M$ programmers baffles me.
node-gyp requires to install this windows "build" bloat and I just lost 6 GB of space after running it.
And for what? Just to be able to install npm packages.
Seriously?

**Comment by AlexandraK** [comment]
And after running `pm remove --global --production windows-build-tools` spaces wasn't freed. So basically I am left with 6 GB of trash who knows where..

**Comment by kuttim** [comment]
You shouldn't install things on internet, if you don't know what you're installing.

**Comment by jacobq** [comment]
> `node-gyp` requires to install this windows "build" bloat and I just lost 6 GB of space after running it. And for what? Just to be able to install npm packages. Seriously?

You only need to have build tools when you want to compile native node modules. That is, C/C++ code compiled specifically for your machine's architecture and node version. You do not need this in order to install pure JavaScript node modules.

Furthermore, if 6GB of storage space on a development machine seems like a lot to you then you may want to consider developing in a more space efficient ecosystem. Node / JS is not known for optimizing space utilization.

> And after running `npm remove --global --production windows-build-tools` space wasn't freed. So basically I am left with 6 GB of trash who knows where.

As mentioned in the README, this package is meant as a convenient to download and install some other software. It is not designed to uninstall those, but you can certainly do so manually. See https://github.com/felixrieseberg/windows-build-tools/issues/68
