### ISSUE TITLE
Unsupported  {"os":"win32"} (current: {"os":"linux","arch":"x64"})

### ISSUE THREAD

**Issue by simonh1000** [felixrieseberg/windows-build-tools#229]
I have a completely fresh install of WSL with nvm (node version 15). ` npm install --global windows-build-tools` results in 

`Unsupported platform for windows-build-tools@5.2.2: wanted {"os":"win32"} (current: {"os":"linux","arch":"x64"})`

**Comment by jacobq** [comment]
Sounds like you are trying to install this in a Linux / non-Windows
environment. This package is for installing some Windows software. It won't
work on other platforms (and is not needed there). What are your intending
to do?

**Comment by amankkg** [comment]
I came here because of `node-gyp` error in WSL (from https://github.com/vaadin/vaadin-connect/issues/150)

**Comment by jacobq** [comment]
> I found this while looking for `node-gyp` error fix in WSL (similar to this [vaadin/vaadin-connect#150](https://github.com/vaadin/vaadin-connect/issues/150))

Hmm, if you're building in WSL I would've thought you'd use the standard Linux build tools rather than the Windows ones.  In that case I believe the "Unsupported platform" error reported is the expected behavior. You may want to take another look at the [`node-gyp` docs here](https://github.com/nodejs/node-gyp#installation).
