### ISSUE TITLE
Can't find PowerShell.exe

### ISSUE THREAD

**Issue by Reyth** [felixrieseberg/windows-build-tools#46]
This is a previously marked error, true but no proper fix was given. The earlier filed issue suggested a fix of adding `WindowsPowerShell/v1.0` to your PATH but, this did not work.
I am on Windows 8.1, using an elevated PowerShell instance.
![err](https://cloud.githubusercontent.com/assets/21691815/22402483/7db24e4e-e61e-11e6-9c2e-63b96b62439e.PNG)

Below is the npm-debug file.
[npm-debug.txt](https://github.com/felixrieseberg/windows-build-tools/files/737351/npm-debug.txt)

**Comment by felixrieseberg** [comment]
The core issue is that we're calling `powershell.exe`, but your system goes "I don't know what you're talking about". This only happens when you changed your system. I'm not entirely sure how you made Windows forget about PowerShell (usually, you can fix it by finding which folder your powershell.exe lives in - and adding it to your PATH), but I _can_ help you test easily whether or not things are okay.

1) Create a script called `test.js` and fill it with the following:

```js
require('child_process').exec('powershell.exe "echo Hi!"`, function (err, r) { console.log(r) }) 
```

2) Run the script `node test.js`
3) If everything is okay, you should see a "Hi!"

**Comment by Reyth** [comment]
`require('child_process').exec(`powershell.exe "echo Hi!"`, function (err, r) { console.log(r) }) ` Something's up, I am not getting any response.

**Comment by felixrieseberg** [comment]
You wouldn't get anything unless Windows can find PowerShell.
