### ISSUE TITLE
install python2.7 even though already installed.

### ISSUE THREAD

**Issue by Nexxado** [felixrieseberg/windows-build-tools#53]
Package installs python2.7 under `%UserProfile%/.windows-build-tools` even though python2.7 is already installed and added to PATH.

**Comment by Mottie** [comment]
I noticed the same problem, but I have python 3.6.1 installed.

**Comment by voltagex** [comment]
Also, this installs 2.7.11 when the latest 2.7 is 2.7.12

**Comment by someja** [comment]
is there a flag to close python install

**Comment by alexdevero** [comment]
The same here. I had Python 2.7.14 installed on my computer before installing build tools. Now, I have two versions - Python 2.7.14 installed by me and Python 2.7.13 installed by build tools. Is there a way to skip Python while installing build tools?

**Comment by diegojsRW** [comment]
+1
Need to add a flag to skip installing Python and/or inform where it's located on machine (e.g npm install -g windows-build-tools python=C:\Portable\python27\python.exe ). It could either "clone" files on that directory, make a symlink or configure gyp to use that python instead of %USERPROFILE%\.windows-build-tools\python27.

**Comment by MrFoxPro** [comment]
+1

**Comment by felixrieseberg** [comment]
This is now fixed!
