### ISSUE TITLE
How to install this without Python?

### ISSUE THREAD

**Issue by E3V3A** [felixrieseberg/windows-build-tools#87]
I'm using Cygwin for most Windows related development and would like to install the `VC++` related tools etc. But I already have both Python2 and 3. 

> It will also install Python 2.7, configuring your machine and npm appropriately.

1. **How can I install this without installing (or trying to configure) Python?**

Also, you mention *Visual Studio*. 

> Visual C++ Build Tools 2015

2. **Does the full VS also get installed?**
3. **What are the `C++ Build tools specific command prompts`?**

**Comment by jacobq** [comment]
> How can I install this without installing (or trying to configure) Python?

I believe this is not currently possible but planned for the future. e.g. https://github.com/felixrieseberg/windows-build-tools/issues/53#issuecomment-353802206

**Comment by jacobq** [comment]
> Does the full VS also get installed?

No, only ]the build tools](http://landinghub.visualstudio.com/visual-cpp-build-tools), since they are all that should be needed. You can see [the URL used for that download here](https://github.com/felixrieseberg/windows-build-tools/blob/5799ed6561df0e235bc228d4782b010c8dd6e7d5/src/constants.js#L7).

> What are the C++ Build tools specific command prompts?

I am not sure exactly what you mean by this question. Installing this `windows-build-tools` package doesn't normally generate any command promptings, as far as I know.

**Comment by E3V3A** [comment]
> I am not sure exactly what you mean by this question.
> "C++ Build tools specific command prompts"

That's how it is written in the readme, and what I was wondering about as well. 
Thanks for response.

**Comment by jacobq** [comment]
Oh, now I see what you're asking about. [The "contents" part of the readme](https://github.com/felixrieseberg/windows-build-tools#contents) quotes from the MS package, see [MSDN info page](https://blogs.msdn.microsoft.com/vcblog/2015/11/02/announcing-visual-c-build-tools-2015-standalone-c-tools-for-build-environments/)

**Comment by E3V3A** [comment]
Thank you! :)
