### ISSUE TITLE
Fails in Node v4.x

### ISSUE THREAD

**Issue by kheston** [felixrieseberg/windows-build-tools#91]
We've been using windows-build-tools for some time in order to build modules for node v4.x alongside VS2017. We're now seeing this error:

```
C:\Users\user\Desktop\project>npm install -g windows-build-tools

> windows-build-tools@2.2.1 postinstall C:\Program Files (x86)\Nodist\bin\node_modules\windows-build-tools
> node ./lib/index.js

C:\Program Files (x86)\Nodist\bin\node_modules\windows-build-tools\lib\utils\single-line-log.js:5
var MOVE_LEFT = Buffer.from('1b5b3130303044', 'hex').toString();
                       ^

TypeError: hex is not a function
    at Function.from (native)
    at Function.from (native)
```

Is there a known workaround?

**Comment by kheston** [comment]
Found a workaround:
`npm install --global windows-build-tools@v1.3.2`

**Comment by jacobq** [comment]
@kheston Yes, 2.x has some breaking changes (though I don't think we have them nicely documented in a change log). As I understand it [supporting MS 2017 build tools](https://github.com/felixrieseberg/windows-build-tools/pull/84) was the main change and [dropping support for node 4.x](https://github.com/felixrieseberg/windows-build-tools/commit/f83bc53f0d8e7cd18d2243702aa1918618b01257) (since it's just a few months away from being end-of-life anyway) was the other one.
