### ISSUE TITLE
ATL/MFC are not installed by default

### ISSUE THREAD

**Issue by pronebird** [felixrieseberg/windows-build-tools#92]
The docs claim ON by default. But I don't see them being installed on my Windows 10 box. I expect them to be installed under `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc`.

As a workaround I went to "Add or Remove programs" and hit "Modify" next to Microsoft Visual C++ Build Tools, tick the ATL/MFC in the appeared dialog. The folder then appeared at the expected location.

**Comment by jacobq** [comment]
@pronebird Which version were you using (latest = 2.2.1?) were you using the `--vs2017` argument to get the 2017 version? The package defaults may have changed, in which case we should update the docs.

**Comment by pronebird** [comment]
@jacobq honestly I have no idea, I just got a clean win10 box and ran `npm install --global --production windows-build-tools`. Must be the latest given I just installed node.js and all that.

**Comment by jacobq** [comment]
@felixrieseberg It looks like the MFC and ATL support [is an optional component / not installed by MS default](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools) and we only specify [`Microsoft.VisualStudio.Workload.VCTools`](https://github.com/felixrieseberg/windows-build-tools/blob/4970e40e32a475268d77959051887c724abe371d/ps1/launch-installer.ps1#L43). Do you recall if this is different than with the 2015 version? It seems to me that we should either update our docs or pass `--add Microsoft.VisualStudio.Component.VC.ATLMFC` etc. to the installer package. Thoughts?

> By default, the Required components will be installed when you install the workload. If you choose to, you can also install the Recommended and Optional components.

**Comment by jacobq** [comment]
@pronebird OK, then you would have gotten the latest. In your case, you can check with `npm ls --global windows-build-tools`.

**Comment by pronebird** [comment]
@jacobq updated my comment. Yes indeed it would be beneficial to update the documentation to outline that ATL/MFC can be installed with certain flag.

**Comment by pronebird** [comment]
@jacobq any suggestion how to workaround that for the time being, any magic switch?

**Comment by jacobq** [comment]
(Can't work on this now but making notes for later)

"[Announcing Visual C++ Build Tools 2015 – standalone C++ tools for build environments](https://blogs.msdn.microsoft.com/vcblog/2015/11/02/announcing-visual-c-build-tools-2015-standalone-c-tools-for-build-environments/)" (11/2015)
"[Announcing the official release of the Visual C++ Build Tools 2015](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/)" (3/2016)
* Visual C++ Compilers (targeting x86, X64 and ARM)
* Visual C++ headers & libraries (CRT & STL)
* Visual C++ build scripts (targeting Windows desktop)
* Microsoft Build Tools 2015 (MSBuild)
* Windows SDK 8.1 (optional, on by default)
* Windows SDK 10 (optional, off by default)
* ATL and MFC (optional, off by default)
* C++ Build tools specific command prompts

"[Introducing the Visual Studio Build Tools](https://blogs.msdn.microsoft.com/vcblog/2016/11/16/introducing-the-visual-studio-build-tools/)" (11/2016)
![2017 installation options](https://msdnshared.blob.core.windows.net/media/2016/11/312.png)

"Contents" section of our current [(v2.2.1) `README.md`](https://github.com/felixrieseberg/windows-build-tools/blob/v2.2.1/README.md#contents) (emphasis added)
* Visual C++ Compilers (targeting x86, X64 and ARM)
* Visual C++ headers & libraries (CRT & STL)
* Visual C++ build scripts (targeting Windows desktop)
* Microsoft Build Tools 2017 (MSBuild)
* Windows SDK 10 (optional, on by default)
* ATL and MFC **(optional, on by default)**
* C++ Build tools specific command prompts

My recommendation is probably that we link to MS' documentation regarding their defaults since `windows-build-tools` appears to be currently just using defaults and passing options from users.

**Comment by jacobq** [comment]
@pronebird, yes, see [the README](https://github.com/felixrieseberg/windows-build-tools/blob/master/README.md#supplying-parameters-to-the-vcc-build-tools) and MS' docs (don't have a link handy -- would have to go hunt. Sometimes it's hard to find docs for older versions of MS products).

**Comment by pronebird** [comment]
@jacobq 

Seems like passing either `/Full` or `/InstallSelectableItems Microsoft.VisualStudio.Workload.VCTools;Microsoft.VisualStudio.Component.VC.ATLMFC` should work for VS2015

**Comment by pronebird** [comment]
Actually even /Full doesn't work, so it seems that `vcc-build-tools-parameters` is broken?

```
npm --add-python-to-path --vcc-build-tools-parameters='[""/F
ull"", ""/Passive""]' install --global windows-build-tools
```

**Comment by jacobq** [comment]
Does `build-tools-log.txt` show the parameters getting passed? (Try w/ `--debug`?)

**Comment by pronebird** [comment]
@jacobq am I right to think that $params is simply overwritten?

`https://github.com/felixrieseberg/windows-build-tools/blob/master/ps1/launch-installer.ps1#L48`

Log seems to be correct:

```
windows-build-tools Installer: Parsing additional arguments for VCC build tools failed: {} +0ms
windows-build-tools Input received: [/Full, /Passive]
```

**Comment by jacobq** [comment]
@felixrieseberg It looks like we're [clobbering parameters here](https://github.com/felixrieseberg/windows-build-tools/blob/v2.2.1/ps1/launch-installer.ps1#L41-L50). Did you [break it here?](https://github.com/felixrieseberg/windows-build-tools/commit/f05abe6d6742559a95fc55d7abded944ccdf20fb#diff-de8eead87838ee815887738e6f6187a8)

**Comment by jacobq** [comment]
@pronebird ha, we both were looking at that at the same time, yeah, that's what it looks like to me. For now, try holding back to previous version. e.g. `npm install --global windows-build-tools@2.1.5` (except with your args)

**Comment by jacobq** [comment]
BTW, if you have time to make a PR to fix this (and bonus points for adding a test to prevent future repeats of this regression) that would be awesome.

**Comment by pronebird** [comment]
@jacobq I have very little knowledge about Powershell so I'd leave this trivial fix to you two. On the side note I've sent a separate PR to improve the error message received from `JSON.parse` (see #95)

**Comment by lygstate** [comment]
There is no option to install atl mfc

**Comment by mikew** [comment]
Not seeing ATL installed, despite being mentioned and enabled here: 
<img width="419" alt="Screen Shot 2019-04-06 at 2 56 11 PM" src="https://user-images.githubusercontent.com/4729/55673270-2ca96a00-587c-11e9-91e6-04b78cc789a5.png">
